version: 2.1
workflows:
  testing:
    jobs:
      - runner-test
      - nhp-abcd
jobs:
  runner-test:
    machine: true
    resource_class: vanandrew/linux
    steps:
      - run: echo "Hi I'm on Runners!"
  nhp-abcd:
    machine: true
    resource_class: vanandrew/linux
    steps:
      - run:
          command: |
            ls /mnt/data
            sudo apt-get update
            sudo apt-get install -y ca-certificates curl gnupg lsb-release
            sudo mkdir -p /etc/apt/keyrings
            sudo curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /etc/apt/keyrings/docker.gpg
            sudo echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
            sudo apt-get update
            sudo apt-get install -y docker-ce docker-ce-cli containerd.io docker-compose-plugin
            sudo docker ps -a