version: 2.1
workflows:
  build-and-run:
    jobs:
      - build
      - run:
          requires:
            - build
jobs:
  build:
    machine: true
    resource_class: vanandrew/linux
    steps:
      - checkout
      - run:
          command: |
            export DOCKER_BUILDKIT=1
            sudo -E docker build . -t vanandrew/nhp-abcd-bids-pipeline -q
            sudo docker system prune -f
          no_output_timeout: 3h
  run:
    machine: true
    resource_class: vanandrew/linux
    steps:
      - run:
          command: |
            ls /data
            ls /output
            sudo docker run -it --rm --name baloo -v /data:/data -v /output:/output --entrypoint="ls /data" vanandrew/nhp-abcd-bids-pipeline
          no_output_timeout: 3h