version: 2.1
workflows:
  build-and-run:
    jobs:
      - build
      - run:
          requires:
            - build
jobs:
  build:
    machine: true
    resource_class: vanandrew/linux
    steps:
      - checkout
      - run:
          command: |
            ./tools/download-templates.sh
            export DOCKER_BUILDKIT=1
            sudo -E docker build . -t vanandrew/nhp-abcd-bids-pipeline -q
            sudo docker system prune -f
          no_output_timeout: 3h
  run:
    machine: true
    resource_class: vanandrew/linux
    steps:
      - run:
          command: |
            sudo docker run -it --rm --name baloo \
              -v ${NHP_DATA_MOUNTPOINT}:/data:ro \
              -v ${NHP_WRITABLE_MOUNTPOINT}:/output \
              -v ${NHP_DATA_MOUNTPOINT}/dcan_nhp_parcellations_20210907/parcellations:/opt/dcan-tools/dcan_bold_proc/templates/parcellations:ro \
              vanandrew/nhp-abcd-bids-pipeline \
              /data/nhp_bids /output --config_file /data/configs/baloo_config.toml
          no_output_timeout: 5h